### ISSUE TITLE
Create a Nuget package for amzinet

### ISSUE THREAD

**Issue by fahadash** [AmziLS/distribution#3]
The library amzinet cannot work with .NET Core because .NET Core prefers to work with libraries coming through Nuget packages as opposed to files placed in the directory.

The Nuget package has to be authentic and come from Amzi's official Nuget account on www.nuget.org to be trusted. The package should also include amzi.dll and a powershell script to add amzi.dll to the project and set the Build Action to `Content` and the Copy-To-Output-Directory to `Copy Always`

**Comment by DennisMerritt** [comment]
Is this something you can do as well?

FYI — the .NET portions of Amzi! were developed by Mary Kroening, who has since passed away.  I have never done much .NET coding myself other than to rebuild the interface as necessary.  So help is definitely appreciated.  (For example, I have not heard of Nuget before.)

Best,
—Dennis



On March 13, 2017 at 10:14:41 AM, fahadash (notifications@github.com) wrote:

The library amzinet cannot work with .NET Core because .NET Core prefers to work with libraries coming through Nuget packages as opposed to files placed in the directory.

The Nuget package has to be authentic and come from Amzi's official Nuget account on www.nuget.org to be trusted. The package should also include amzi.dll and a powershell script to add amzi.dll to the project and set the Build Action to Content and the Copy-To-Output-Directory to Copy Always

**Comment by fahadash** [comment]
Please create an official Amzi Inc account on Nuget.org. What I will do is create a NUSPEC file which contains the meta-data for packages, I can point you to creating a package using the NUSPEC (or I can just add a package for you, I want Amzi to be the trusted authority signing the packages so people can know the package is authentic). You can then Upload the package as a "Pre-Release" and have a few developers test it, once it passes, you can change the package status to Release.

**Comment by DennisMerritt** [comment]
I’ve created a Nuget account.
Amzi
and
Amzi10xProlog

I’m happy to leave this all in your hands, I know there are many others using .NET, but I don’t know who they are.

Let me know when you want me to pull something.

I guess I’m a bit confused about Nuget packages fit with open source.  Would we put the package up on GitHub?

Best,
—Dennis



On March 14, 2017 at 10:16:29 AM, fahadash (notifications@github.com) wrote:

Please create an official Amzi Inc account on Nuget.org. What I will do is create a NUSPEC file which contains the meta-data for packages, I can point you to creating a package using the NUSPEC (or I can just add a package for you, I want Amzi to be the trusted authority signing the packages so people can know the package is authentic). You can then Upload the package as a "Pre-Release" and have a few developers test it, once it passes, you can change the package status to Release.

**Comment by fahadash** [comment]
Please change your nuget password, all these comments are on public domain
